config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :favorites

  resources :products do
    member do
      post :add_to_cart
      post :favorite
      post :unfavorite
      put "like", to: "products#upvote"
    end
    resources :reviews
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items do
    member do
      post :add_quantity
      post :remove_quantity
    end
  end
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
    end
  end

  namespace :account do
    resources :users
    resources :orders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  acts_as_votable
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :fans, :through => :favorites, :source => :user 
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  layout "admin"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

   def edit
     @product = Product.find(params[:id])
   end

   def update
     @product = Product.find(params[:id])
     if @product.save(product_params)
       redirect_to admin_products_path
     else
       render :edit
     end
   end

   def destroy
     @product = Product.find(params[:id])
     @product.destroy
     redirect_to admin_products_path
   end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
    current_cart.add_product_to_cart(@product)
    flash[:notice] = "成功将#{@product.title}加入购物车"
  else
    flash[:warning] = "你的购物车内已有此物件"
  end
    redirect_to :back
  end

  def upvote
    @product = Product.find(params[:id])
    @product.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @product=Product.find(params[:id])
    @product.downvote_by current_user
    redirect_to :back
  end

  def favorite
    @product = Product.find(params[:id])
    current_user.favorite_products << @product
    flash[:notice] = "您已收藏宝贝"
    redirect_to :back
  end

  def unfavorite
    @product = Product.find(params[:id])
    current_user.favorite_products.delete(@product)
    flash[:notice] = "您已取消收藏宝贝"
    redirect_to :back
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.image.present? %>
          <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= product.title %> ￥ <%= product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
 <ol class="breadcrumb">
    <li><a href="<%= root_path %>">所有宝贝</a></li>
    <li><a href="<%= @product %>"><%= @product.title %></a></li>
  </ol>

<div class="container">
  <div class="col-md-6">
    <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="details" style="margin-top:50px;">
        <h3 class="product-title"><%= @product.title %></h3>
        <div class="price-service">
          <p class="price">原价 <span class="rmb">￥ </span><span class="msrp"><%= @product.msrp.to_i %></span> 元</p>
          <p class="price">现价 <span class="rmb">￥ </span><span class="price"><%= @product.price %></span> 元</p>
          <p class="service">服务 <span class="service-detail">7天无忧退货 | 48小时快速退款 | 正品保证</span></p>
        </div>
        <div class="quantity-size">
          <p class="delivery">运费 <span class="delivery">全场包邮</span></p>
          <p class="quantity">库存 <span class="quantity"><%= @product.quantity %></span> 件 </p>
          <!-- <p>购买: &nbsp &nbsp &nbsp<input type="text" style="width:50px" name="quantity" value="1" />&nbsp件</p> -->
        </div>
        <div class="action">
        <div class="col-md-8" >
             <% if @product.quantity.present? && @product.quantity > 0 %>
                <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post,
                            class: "add-to-cart btn btn-block") %>
             <% else %>
               已销售一空，无法购买
             <% end %>
        </div>
        <div class="col-md-2" >
          <% if current_user %>
           <% if !current_user.is_fan_of?(@product) %>
             <%= link_to favorite_product_path(@product), :class => "like btn btn-default", method: :post do %>
               <i class="fa fa-heart fa-lg"></i>
             <% end %>
           <% else %>
             <%= link_to unfavorite_product_path(@product), :class => "unlike btn btn-default", method: :post do %>
               <i class="fa fa-heart fa-lg"></i>
             <% end %>
           <% end %>
         <% else %>
           <%= link_to favorite_product_path(@product), :class => "like btn btn-default",method: :post do %>
             <i class="fa fa-heart fa-lg"></i>
           <% end %>
         <% end %>
        </div>

        <i class="fa fa-heart" style="font-size:20px;color:red"></i>（<%= @product.fans.count %>）
        <br>
        <%= link_to like_product_path(@product), method: :put do %>
        <i class="fa fa-thumbs-up" style="font-size:20px"></i>（<%= @product.get_upvotes.size %>）
        <% end %>
   </div><!-- End of product show page -->
</div>


<div class="row product_description col-md-12">
    <div class="tabs" >
      <div class="tabbable-panel">
        <div class="tabbable-line">
          <ul class="nav nav-tabs">
            <li role="presentation" class="active">
              <a href="#tab_default_1" data-toggle="tab">宝贝详情</a>

            </li>
            <li>
              <a href="#tab_default_2" data-toggle="tab">宝贝评价(<%= @product.reviews.count %>) </a>
            </li>
          </ul>
          <br />
          <div class="tab-content">
            <div class="tab-pane active" id="tab_default_1">
               <p class="product-description"><%= @product.description.html_safe %></p>
               <p class="product-description2 text-center">产品展示</p>
                <!--商品大图展示 -->
               <div class="faq">
                 <p class="faq-title text-center">常见问题</p>
                 <p class="question">使用什么快递发货？</p>
                 <p class="answer">伴客默认使用顺丰快递发货，配送范围覆盖全国大部分地区（港澳台地区除外）。</p>
                 <p class="question">如何申请退货？</p>
                 <p class="answer">
                   1.自收到商品之日起7日内，顾客可申请无忧退货，退款将原路返还，不同的银行处理时间不同，预计1-5个工作日到账；<br />
                   2.退货流程：<br />
                   确认收货-申请退货-客服审核通过-用户寄回商品-仓库签收验货-退款审核-退款完成；<br />
                   3.因MONSOON产生的退货，如质量问题，退货邮费由MONSOON承担，退款完成后钱款将沿原渠道返还。因客户个人原因产生的退货，购买和寄回运费由客户个人承担。<br />
                 </p>
                 <p class="question">如何开具发票？</p>
                 <p class="answer">如需开具普通发票，请在下单时联系客服办理，我们将虽货物一起快递给您；</p>
               </div>
            </div><!-- End of tab_default_1 -->

            <div class="tab-pane" id="tab_default_2">
                <div class="row">
                  <div class="col-sm-12 ">
                    <h4>
                      <%= @product.reviews.count %> Reviews
                    </h4>
                    <hr>
                    <div >
                      <%= render @product.reviews%>
                      <%= render "reviews/form"%>
                    </div>
                  </div>
                </div>
              </div><!-- End of tab_default_2 -->
            </div><!-- End of tab-content -->
          </div><!-- End of tabbable-line -->
        </div><!-- End of tabbable-panel -->
      </div><!-- End of tabs -->
    </div><!-- End of product description & reviews -->
</div><!-- End of product show page -->